
name: Python CI
on:
  push:
    branches:
      - master
      - feature/**
      - bugfix/**
  pull_request:
    branches: master
jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      
    - name: Get Dependencies
      run: pip3 install -r requirements.txt

    - name: Run Unit Tests
      run: python3 -m unittest -v
  test-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      
    - name: Get Dependencies
      run: pip3 install -r requirements.txt

    - name: Run Unit Tests
      run: python3 -m unittest -v
  test-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      
    - name: Get Dependencies
      run: pip install -r requirements.txt

    - name: Run Unit Tests
      run: python -m unittest -v
