name: Python CI
on:
  push:
    branches:
      - master
      - dev
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - master
      - dev
jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0

    - name: Get Dependencies
      run: |
        sudo apt-get install -y python3-setuptools
        sudo --set-home pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run Unit Tests
      run: python3 -m unittest -v
  test-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0

    - name: Get Dependencies
      run: |
        sudo --set-home pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run Unit Tests
      run: python3 -m unittest -v
  test-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0

    - name: Get Dependencies
      run: pip install -r requirements.txt

    - name: Run Unit Tests
      run: python -m unittest -v
